name: issues

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  irc:
    runs-on: ubuntu-latest
    steps:
      - name: "notify: new"
        uses: rectalogic/notify-irc@v1
        if: github.event.issue.state == 'open'
        with:
          server: chat.freenode.net
          nickname: cala-notify
          channel: "#calamares"
          message: "[${{ github.event.issue.title }}](${{ github.event.issue.html_url }}) opened by ${{ github.actor }}"
      - name: "notify: closed"
        uses: rectalogic/notify-irc@v1
        if: github.event.issue.state != 'open'
        with:
          server: chat.freenode.net
          nickname: cala-notify
          channel: "#calamares"
          message: "[${{ github.event.issue.title }}](${{ github.event.issue.html_url }}) closed by ${{ github.actor }}"
